//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WixWPFWizardBA {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localisation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localisation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WixWPFWizardBA.Localisation", typeof(Localisation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding product {0} to list of bundles to update..
        /// </summary>
        public static string BootstrapperLog_AddingProductToBundlesToUpdate {
            get {
                return ResourceManager.GetString("BootstrapperLog_AddingProductToBundlesToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplyAction called..
        /// </summary>
        public static string BootstrapperLog_ApplyActionCalled {
            get {
                return ResourceManager.GetString("BootstrapperLog_ApplyActionCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt to downgrade the application was made..
        /// </summary>
        public static string BootstrapperLog_AttemptToDowngrade {
            get {
                return ResourceManager.GetString("BootstrapperLog_AttemptToDowngrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt to reinstall the application was made..
        /// </summary>
        public static string BootstrapperLog_AttemptToReinstall {
            get {
                return ResourceManager.GetString("BootstrapperLog_AttemptToReinstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bootstrapper ApplyComplete with status {0}, restart required: {1}, previous burn state: {2}.
        /// </summary>
        public static string BootstrapperLog_BootstrapperApplyComplete {
            get {
                return ResourceManager.GetString("BootstrapperLog_BootstrapperApplyComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bootstrapper detect complete, resume: {0}, launch action: {1}.
        /// </summary>
        public static string BootstrapperLog_BootstrapperDetectComplete {
            get {
                return ResourceManager.GetString("BootstrapperLog_BootstrapperDetectComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bootstrapper Detect resulted in DetectedAbsent..
        /// </summary>
        public static string BootstrapperLog_BootstrapperDetectedAbsent {
            get {
                return ResourceManager.GetString("BootstrapperLog_BootstrapperDetectedAbsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bootstrapper Detect resulted in DetectedPresent..
        /// </summary>
        public static string BootstrapperLog_BootstrapperDetectedPresent {
            get {
                return ResourceManager.GetString("BootstrapperLog_BootstrapperDetectedPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bootstrapper found bundle version {0} at {1}, current version: {2}.
        /// </summary>
        public static string BootstrapperLog_BootstrapperFoundBundleVersion {
            get {
                return ResourceManager.GetString("BootstrapperLog_BootstrapperFoundBundleVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bootstrapper handled error {0}: {1}.
        /// </summary>
        public static string BootstrapperLog_BootstrapperHandledError {
            get {
                return ResourceManager.GetString("BootstrapperLog_BootstrapperHandledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bootstrapper has called {0}.
        /// </summary>
        public static string BootstrapperLog_BootstrapperHasCalled {
            get {
                return ResourceManager.GetString("BootstrapperLog_BootstrapperHasCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bootstrapper has called {0}, Download source: {1}.
        /// </summary>
        public static string BootstrapperLog_BootstrapperHasCalledAndSource {
            get {
                return ResourceManager.GetString("BootstrapperLog_BootstrapperHasCalledAndSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bootstrapper has called {0}, package id: {1}.
        /// </summary>
        public static string BootstrapperLog_BootstrapperHasCalledWithPackageID {
            get {
                return ResourceManager.GetString("BootstrapperLog_BootstrapperHasCalledWithPackageID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bootstrapper planning MsiFeature {0} of {1}.
        /// </summary>
        public static string BootstrapperLog_BootstrapperPlanningMsiFeature {
            get {
                return ResourceManager.GetString("BootstrapperLog_BootstrapperPlanningMsiFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bootstrapper received error code {0}: {1}.
        /// </summary>
        public static string BootstrapperLog_BootstrapperReceivedErrorCode {
            get {
                return ResourceManager.GetString("BootstrapperLog_BootstrapperReceivedErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bootstrapper shutting down..
        /// </summary>
        public static string BootstrapperLog_BootstrapperShuttingDown {
            get {
                return ResourceManager.GetString("BootstrapperLog_BootstrapperShuttingDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} changed: {1}.
        /// </summary>
        public static string BootstrapperLog_Changed {
            get {
                return ResourceManager.GetString("BootstrapperLog_Changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for upgrade: product code: {0}, bundleId = {1}.
        /// </summary>
        public static string BootstrapperLog_CheckForUpgrade {
            get {
                return ResourceManager.GetString("BootstrapperLog_CheckForUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected related MSI package: {0}.
        /// </summary>
        public static string BootstrapperLog_DetectedRelatedMSIPackage {
            get {
                return ResourceManager.GetString("BootstrapperLog_DetectedRelatedMSIPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bootstrapper_DetectRelatedBundle: Bundle {0}, operation: {1}.
        /// </summary>
        public static string BootstrapperLog_DetectRelatedBundle {
            get {
                return ResourceManager.GetString("BootstrapperLog_DetectRelatedBundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception trying to open in Explorer the path {0}. Exception message: {1}.
        /// </summary>
        public static string BootstrapperLog_ExceptionOpeningExplorerWindow {
            get {
                return ResourceManager.GetString("BootstrapperLog_ExceptionOpeningExplorerWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to detect updates, status {0}.
        /// </summary>
        public static string BootstrapperLog_FailedToDetectUpdates {
            get {
                return ResourceManager.GetString("BootstrapperLog_FailedToDetectUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A newer version of {0} is already installed..
        /// </summary>
        public static string BootstrapperLog_NewerVersionInstalled {
            get {
                return ResourceManager.GetString("BootstrapperLog_NewerVersionInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package detection complete: {0}, State: {1}.
        /// </summary>
        public static string BootstrapperLog_PackageDetectionComplete {
            get {
                return ResourceManager.GetString("BootstrapperLog_PackageDetectionComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planning action with (0).
        /// </summary>
        public static string BootstrapperLog_PlanningActionWith {
            get {
                return ResourceManager.GetString("BootstrapperLog_PlanningActionWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting bundle to Absent..
        /// </summary>
        public static string BootstrapperLog_SettingBundleToAbsent {
            get {
                return ResourceManager.GetString("BootstrapperLog_SettingBundleToAbsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting error code: {0}.
        /// </summary>
        public static string BootstrapperLog_SettingErrorCode {
            get {
                return ResourceManager.GetString("BootstrapperLog_SettingErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting error message: {0}.
        /// </summary>
        public static string BootstrapperLog_SettingErrorMessage {
            get {
                return ResourceManager.GetString("BootstrapperLog_SettingErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting the currently selected launch action to {0}, as selected by the bootstrapper..
        /// </summary>
        public static string BootstrapperLog_SettingLaunchAction {
            get {
                return ResourceManager.GetString("BootstrapperLog_SettingLaunchAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This version of {0} is already installed..
        /// </summary>
        public static string BootstrapperLog_VersionAlreadyInstalled {
            get {
                return ResourceManager.GetString("BootstrapperLog_VersionAlreadyInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Error while installing.
        /// </summary>
        public static string BootstrapperManager_InstallErrorMessageTitle {
            get {
                return ResourceManager.GetString("BootstrapperManager_InstallErrorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A newer version of is {0} already installed.
        /// </summary>
        public static string BootstrapperManager_NewerVersionInstalledMessage {
            get {
                return ResourceManager.GetString("BootstrapperManager_NewerVersionInstalledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Newer version already installed.
        /// </summary>
        public static string BootstrapperManager_NewerVersionInstalledTitle {
            get {
                return ResourceManager.GetString("BootstrapperManager_NewerVersionInstalledTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string BrowseButtonText {
            get {
                return ResourceManager.GetString("BrowseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellation is already in progress..
        /// </summary>
        public static string CancelAlreadyInProgressMessageBoxBody {
            get {
                return ResourceManager.GetString("CancelAlreadyInProgressMessageBoxBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Setup.
        /// </summary>
        public static string CancelAlreadyInProgressMessageBoxTitle {
            get {
                return ResourceManager.GetString("CancelAlreadyInProgressMessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel the installation of {0}?.
        /// </summary>
        public static string CancelDialogBody {
            get {
                return ResourceManager.GetString("CancelDialogBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Setup.
        /// </summary>
        public static string CancelDialogTitle {
            get {
                return ResourceManager.GetString("CancelDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t cancel the installation at this stage..
        /// </summary>
        public static string CancelUnavailableMessageBoxBody {
            get {
                return ResourceManager.GetString("CancelUnavailableMessageBoxBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Setup.
        /// </summary>
        public static string CancelUnavailableMessageBoxTitle {
            get {
                return ResourceManager.GetString("CancelUnavailableMessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications (*.exe)|*.exe.
        /// </summary>
        public static string ClientConfigurationDialog_BrowseDlgFilter {
            get {
                return ResourceManager.GetString("ClientConfigurationDialog_BrowseDlgFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the application used to open text based forms..
        /// </summary>
        public static string ClientConfigurationDialog_BrowseDlgTitle {
            get {
                return ResourceManager.GetString("ClientConfigurationDialog_BrowseDlgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B_rowse. . ..
        /// </summary>
        public static string ClientConfigurationPage_Browse {
            get {
                return ResourceManager.GetString("ClientConfigurationPage_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string ClientConfigurationPage_Server {
            get {
                return ResourceManager.GetString("ClientConfigurationPage_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name or hostname and port number of the Perforce server that clients connect to. Omit hostname for connecting to a local server..
        /// </summary>
        public static string ClientConfigurationPage_ServerDesc {
            get {
                return ResourceManager.GetString("ClientConfigurationPage_ServerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Editing Application.
        /// </summary>
        public static string ClientConfigurationPage_TextEditingApplication {
            get {
                return ResourceManager.GetString("ClientConfigurationPage_TextEditingApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application used to open text based forms..
        /// </summary>
        public static string ClientConfigurationPage_TextEditingApplicationDesc {
            get {
                return ResourceManager.GetString("ClientConfigurationPage_TextEditingApplicationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Configuration.
        /// </summary>
        public static string ClientConfigurationPage_TitleText {
            get {
                return ResourceManager.GetString("ClientConfigurationPage_TitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string ClientConfigurationPage_UserName {
            get {
                return ResourceManager.GetString("ClientConfigurationPage_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perforce user name for connecting to a Perforce server..
        /// </summary>
        public static string ClientConfigurationPage_UserNameDesc {
            get {
                return ResourceManager.GetString("ClientConfigurationPage_UserNameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default value of &quot;perforce:1666&quot; in the Server field likely needs to be updated. Contact your Perforce administrator, if you are unsure of the name of your server..
        /// </summary>
        public static string DefaultPortWarningDialog_Text {
            get {
                return ResourceManager.GetString("DefaultPortWarningDialog_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This installer can only be run on a 64-bit operating system. A 32-bit installer for Helix Plugin for File Explorer is available {0}..
        /// </summary>
        public static string FinishErrorPage_ErrorOSx86MSIx64 {
            get {
                return ResourceManager.GetString("FinishErrorPage_ErrorOSx86MSIx64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helix Plugin for File Explorer requires that you have at least Perforce Visual Client (P4V) 2019.2/1883366 installed. Download from {0} then run this installer again..
        /// </summary>
        public static string FinishErrorPage_ErrorP4VVersion {
            get {
                return ResourceManager.GetString("FinishErrorPage_ErrorP4VVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a 64-bit P4EXP installed, but this installer will install a 32-bit P4EXP. Though it&apos;s not recommended, if you want to install 32-bit P4EXP you need to first uninstall the 64-bit P4EXP..
        /// </summary>
        public static string FinishErrorPage_ErrorUpgradex64Withx86 {
            get {
                return ResourceManager.GetString("FinishErrorPage_ErrorUpgradex64Withx86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a 32-bit P4EXP installed, but this installer will install a 64-bit P4EXP. If you want to install 64-bit P4EXP, which is recommended, you need to first uninstall the 32-bit P4EXP..
        /// </summary>
        public static string FinishErrorPage_ErrorUpgradex86Withx64 {
            get {
                return ResourceManager.GetString("FinishErrorPage_ErrorUpgradex86Withx64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The installation was cancelled..
        /// </summary>
        public static string FinishErrorPage_FinishErrorCanceled {
            get {
                return ResourceManager.GetString("FinishErrorPage_FinishErrorCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet connection error..
        /// </summary>
        public static string FinishErrorPage_FinishErrorConnectionError {
            get {
                return ResourceManager.GetString("FinishErrorPage_FinishErrorConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t download additional packages from the internet..
        /// </summary>
        public static string FinishErrorPage_FinishErrorCouldntDownloadInstallPackages {
            get {
                return ResourceManager.GetString("FinishErrorPage_FinishErrorCouldntDownloadInstallPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t retrieve additional packages..
        /// </summary>
        public static string FinishErrorPage_FinishErrorCouldntRetrieveInstallPackages {
            get {
                return ResourceManager.GetString("FinishErrorPage_FinishErrorCouldntRetrieveInstallPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred..
        /// </summary>
        public static string FinishErrorPage_FinishErrorUnknown {
            get {
                return ResourceManager.GetString("FinishErrorPage_FinishErrorUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.perforce.com/downloads/helix-visual-client-p4v.
        /// </summary>
        public static string FinishErrorPage_P4VDownloadLink {
            get {
                return ResourceManager.GetString("FinishErrorPage_P4VDownloadLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show log file(s).
        /// </summary>
        public static string FinishErrorPage_ShowLogFiles {
            get {
                return ResourceManager.GetString("FinishErrorPage_ShowLogFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Exit.
        /// </summary>
        public static string FinishPage_ExitButtonText {
            get {
                return ResourceManager.GetString("FinishPage_ExitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished installing.
        /// </summary>
        public static string FinishPage_FinishedInstalling {
            get {
                return ResourceManager.GetString("FinishPage_FinishedInstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished repairing.
        /// </summary>
        public static string FinishPage_FinishedRepairing {
            get {
                return ResourceManager.GetString("FinishPage_FinishedRepairing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished uninstalling.
        /// </summary>
        public static string FinishPage_FinishedUninstalling {
            get {
                return ResourceManager.GetString("FinishPage_FinishedUninstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished upgrading.
        /// </summary>
        public static string FinishPage_FinishedUpgrading {
            get {
                return ResourceManager.GetString("FinishPage_FinishedUpgrading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully installed {0}.
        /// </summary>
        public static string FinishPage_InstallationFinishedSuccessfully {
            get {
                return ResourceManager.GetString("FinishPage_InstallationFinishedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string FinishPage_License {
            get {
                return ResourceManager.GetString("FinishPage_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.perforce.com/perforce/r{0}/user/p4exp_license.txt.
        /// </summary>
        public static string FinishPage_LicenseURL {
            get {
                return ResourceManager.GetString("FinishPage_LicenseURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been successfully modified..
        /// </summary>
        public static string FinishPage_ModificationFinishedSuccessfully {
            get {
                return ResourceManager.GetString("FinishPage_ModificationFinishedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Notes.
        /// </summary>
        public static string FinishPage_ReleaseNotes {
            get {
                return ResourceManager.GetString("FinishPage_ReleaseNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.perforce.com/perforce/r{0}/user/p4expnotes.txt.
        /// </summary>
        public static string FinishPage_ReleaseNotesURL {
            get {
                return ResourceManager.GetString("FinishPage_ReleaseNotesURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember to restart File Explorer or your system later..
        /// </summary>
        public static string FinishPage_RememberToRestartExplorer {
            get {
                return ResourceManager.GetString("FinishPage_RememberToRestartExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember to restart your system later..
        /// </summary>
        public static string FinishPage_RememberToRestartSystem {
            get {
                return ResourceManager.GetString("FinishPage_RememberToRestartSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been successfully repaired..
        /// </summary>
        public static string FinishPage_RepairFinishedSuccessfully {
            get {
                return ResourceManager.GetString("FinishPage_RepairFinishedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Restart now.
        /// </summary>
        public static string FinishPage_RestartButtonText {
            get {
                return ResourceManager.GetString("FinishPage_RestartButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To complete the installation, File Explorer must be restarted. File Explorer windows, including the desktop, will be reopened.
        ///
        ///Warning! Restarting File Explorer may interrupt file copy/move operations, and may cause certain processes to halt..
        /// </summary>
        public static string FinishPage_RestartExplorerRequired {
            get {
                return ResourceManager.GetString("FinishPage_RestartExplorerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Restart Explorer.
        /// </summary>
        public static string FinishPage_RestartExplorerText {
            get {
                return ResourceManager.GetString("FinishPage_RestartExplorerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must restart your system for the configuration changes to take effect..
        /// </summary>
        public static string FinishPage_RestartWarning {
            get {
                return ResourceManager.GetString("FinishPage_RestartWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Documentation.
        /// </summary>
        public static string FinishPage_TechnicalDocumentation {
            get {
                return ResourceManager.GetString("FinishPage_TechnicalDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.perforce.com/perforce/r{0}/manuals/p4exp/Content/P4EXP/Home-p4exp.html.
        /// </summary>
        public static string FinishPage_TechnicalDocumentationURL {
            get {
                return ResourceManager.GetString("FinishPage_TechnicalDocumentationURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been successfully removed..
        /// </summary>
        public static string FinishPage_UninstallFinishedSuccessfully {
            get {
                return ResourceManager.GetString("FinishPage_UninstallFinishedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully upgraded {0}.
        /// </summary>
        public static string FinishPage_UpgradeFinishedSuccessfully {
            get {
                return ResourceManager.GetString("FinishPage_UpgradeFinishedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new folders in the path..
        /// </summary>
        public static string FolderBrowserDialog_PathDesc {
            get {
                return ResourceManager.GetString("FolderBrowserDialog_PathDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path:.
        /// </summary>
        public static string FolderBrowserDialog_PathTitle {
            get {
                return ResourceManager.GetString("FolderBrowserDialog_PathTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Current Destination Folder.
        /// </summary>
        public static string FolderBrowserDialog_Title {
            get {
                return ResourceManager.GetString("FolderBrowserDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Repair.
        /// </summary>
        public static string MaintenancePage_Repair {
            get {
                return ResourceManager.GetString("MaintenancePage_Repair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair installation errors. This option fixes missing or corrupted files, shortcuts, and registry entries..
        /// </summary>
        public static string MaintenancePage_RepairDesc {
            get {
                return ResourceManager.GetString("MaintenancePage_RepairDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance.
        /// </summary>
        public static string MaintenancePage_Title {
            get {
                return ResourceManager.GetString("MaintenancePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Uninstall.
        /// </summary>
        public static string MaintenancePage_Uninstall {
            get {
                return ResourceManager.GetString("MaintenancePage_Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall {0} from this system..
        /// </summary>
        public static string MaintenancePage_UninstallDesc {
            get {
                return ResourceManager.GetString("MaintenancePage_UninstallDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No client/workspace files, server database files, or proxy cache files will be removed when this option is used..
        /// </summary>
        public static string MaintenancePage_UninstallDesc2 {
            get {
                return ResourceManager.GetString("MaintenancePage_UninstallDesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework 4.5.
        /// </summary>
        public static string Package_Netfx45Redist {
            get {
                return ResourceManager.GetString("Package_Netfx45Redist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P4EXP Msi.
        /// </summary>
        public static string PackageConfiguration_PackageList_P4EXP_msi {
            get {
                return ResourceManager.GetString("PackageConfiguration_PackageList_P4EXP_msi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planning installation of {0}....
        /// </summary>
        public static string PlanPage_PlanningMessage {
            get {
                return ResourceManager.GetString("PlanPage_PlanningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing additional components {0}.
        /// </summary>
        public static string ProgressPage_InstallingComponentsTextMain {
            get {
                return ResourceManager.GetString("ProgressPage_InstallingComponentsTextMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This process may take from several seconds to several hours to complete..
        /// </summary>
        public static string ProgressPage_InstallingTextLine1 {
            get {
                return ResourceManager.GetString("ProgressPage_InstallingTextLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing components will be downloaded from the internet automatically..
        /// </summary>
        public static string ProgressPage_InstallingTextLine2 {
            get {
                return ResourceManager.GetString("ProgressPage_InstallingTextLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing {0}.
        /// </summary>
        public static string ProgressPage_InstallingTextMain {
            get {
                return ResourceManager.GetString("ProgressPage_InstallingTextMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caching {0}.
        /// </summary>
        public static string ProgressPage_ProgressCachingEntryText {
            get {
                return ResourceManager.GetString("ProgressPage_ProgressCachingEntryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying {0}.
        /// </summary>
        public static string ProgressPage_ProgressCopyEntryText {
            get {
                return ResourceManager.GetString("ProgressPage_ProgressCopyEntryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading {0}.
        /// </summary>
        public static string ProgressPage_ProgressDownloadEntryText {
            get {
                return ResourceManager.GetString("ProgressPage_ProgressDownloadEntryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string ProgressPage_ProgressExecuteEntryText {
            get {
                return ResourceManager.GetString("ProgressPage_ProgressExecuteEntryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting {0}.
        /// </summary>
        public static string ProgressPage_ProgressExtractEntryText {
            get {
                return ResourceManager.GetString("ProgressPage_ProgressExtractEntryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repairing {0}.
        /// </summary>
        public static string ProgressPage_RepairingTextMain {
            get {
                return ResourceManager.GetString("ProgressPage_RepairingTextMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string ProgressPage_Title {
            get {
                return ResourceManager.GetString("ProgressPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total progress: {0}%.
        /// </summary>
        public static string ProgressPage_TotalProgressText {
            get {
                return ResourceManager.GetString("ProgressPage_TotalProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling {0}.
        /// </summary>
        public static string ProgressPage_UninstallingTextMain {
            get {
                return ResourceManager.GetString("ProgressPage_UninstallingTextMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We recommend that you visit the website and check out what&apos;s new..
        /// </summary>
        public static string ProgressPage_UpdatingTextLine2 {
            get {
                return ResourceManager.GetString("ProgressPage_UpdatingTextLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrading {0}.
        /// </summary>
        public static string ProgressPage_UpgradingTextMain {
            get {
                return ResourceManager.GetString("ProgressPage_UpgradingTextMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to review or change any of your settings, click Back..
        /// </summary>
        public static string ReadyToInstallPage_Desc {
            get {
                return ResourceManager.GetString("ReadyToInstallPage_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to Install.
        /// </summary>
        public static string ReadyToInstallPage_Title {
            get {
                return ResourceManager.GetString("ReadyToInstallPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ch_ange. . ..
        /// </summary>
        public static string SelectApplicationsPage_ChangeButtonText {
            get {
                return ResourceManager.GetString("SelectApplicationsPage_ChangeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary install directory:.
        /// </summary>
        public static string SelectApplicationsPage_DirectoryTitle {
            get {
                return ResourceManager.GetString("SelectApplicationsPage_DirectoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Helix Plugin for File Explorer enables you to perform Helix Core operations directly from File Explorer..
        /// </summary>
        public static string SelectApplicationsPage_ProductDescription {
            get {
                return ResourceManager.GetString("SelectApplicationsPage_ProductDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helix Plugin for File Explorer (P4EXP).
        /// </summary>
        public static string SelectApplicationsPage_ProductName {
            get {
                return ResourceManager.GetString("SelectApplicationsPage_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Destination.
        /// </summary>
        public static string SelectApplicationsPage_SelectApplicationsText {
            get {
                return ResourceManager.GetString("SelectApplicationsPage_SelectApplicationsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version: {0}.
        /// </summary>
        public static string SelectApplicationsPage_Version {
            get {
                return ResourceManager.GetString("SelectApplicationsPage_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Server field specifies the location of the Perforce server. This value was likely given to you by your Perforce administrator..
        /// </summary>
        public static string ServerHelpDialog_Text1 {
            get {
                return ResourceManager.GetString("ServerHelpDialog_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location can be specified in multiple ways depending upon your configuration. Below are some supported formats:.
        /// </summary>
        public static string ServerHelpDialog_Text2 {
            get {
                return ResourceManager.GetString("ServerHelpDialog_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * &lt;hostname&gt;:&lt;port number&gt;.
        /// </summary>
        public static string ServerHelpDialog_Text3 {
            get {
                return ResourceManager.GetString("ServerHelpDialog_Text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * &lt;IP address&gt;:&lt;port number&gt;.
        /// </summary>
        public static string ServerHelpDialog_Text4 {
            get {
                return ResourceManager.GetString("ServerHelpDialog_Text4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * &lt;zeroconf name&gt; (Server must have Zeroconf enabled).
        /// </summary>
        public static string ServerHelpDialog_Text5 {
            get {
                return ResourceManager.GetString("ServerHelpDialog_Text5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * &lt;hostname&gt; (Server must be on port 1666).
        /// </summary>
        public static string ServerHelpDialog_Text6 {
            get {
                return ResourceManager.GetString("ServerHelpDialog_Text6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * &lt;port number&gt; (Server must be local).
        /// </summary>
        public static string ServerHelpDialog_Text7 {
            get {
                return ResourceManager.GetString("ServerHelpDialog_Text7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * &lt;TCP/SSL prefix&gt;:&lt;hostname&gt;:&lt;port number&gt;.
        /// </summary>
        public static string ServerHelpDialog_Text8 {
            get {
                return ResourceManager.GetString("ServerHelpDialog_Text8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete settings, preferences, and service parameters of any products being uninstalled..
        /// </summary>
        public static string UninstallPage_DeleteSettings {
            get {
                return ResourceManager.GetString("UninstallPage_DeleteSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string UninstallPage_Title {
            get {
                return ResourceManager.GetString("UninstallPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To uninstall {0} click Uninstall..
        /// </summary>
        public static string UninstallPage_ToUninstall {
            get {
                return ResourceManager.GetString("UninstallPage_ToUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To start the upgrade click Upgrade..
        /// </summary>
        public static string UpgradePage_Desc {
            get {
                return ResourceManager.GetString("UpgradePage_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrading the {0} Installation.
        /// </summary>
        public static string UpgradePage_Title {
            get {
                return ResourceManager.GetString("UpgradePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This installer is for a 32-bit operating system. We strongly recommend you download and install Helix Plugin for File Explorer using the Windows 64-bit installer, available {0}..
        /// </summary>
        public static string WarningPage_Desc {
            get {
                return ResourceManager.GetString("WarningPage_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string WarningPage_Title {
            get {
                return ResourceManager.GetString("WarningPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a restart pending. Please restart your computer before attempting to install {0}..
        /// </summary>
        public static string WixBootstrapper_RestartPendingDialogBody {
            get {
                return ResourceManager.GetString("WixBootstrapper_RestartPendingDialogBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Setup.
        /// </summary>
        public static string WixBootstrapper_RestartPendingDialogTitle {
            get {
                return ResourceManager.GetString("WixBootstrapper_RestartPendingDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; _Back.
        /// </summary>
        public static string Wizard_BackButtonText {
            get {
                return ResourceManager.GetString("Wizard_BackButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path entered is not valid..
        /// </summary>
        public static string Wizard_BadPath {
            get {
                return ResourceManager.GetString("Wizard_BadPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Cancel.
        /// </summary>
        public static string Wizard_CancelButtonText {
            get {
                return ResourceManager.GetString("Wizard_CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close.
        /// </summary>
        public static string Wizard_CloseButtonText {
            get {
                return ResourceManager.GetString("Wizard_CloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Done.
        /// </summary>
        public static string Wizard_DoneButtonText {
            get {
                return ResourceManager.GetString("Wizard_DoneButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing {0}.
        /// </summary>
        public static string Wizard_HeaderInstalling {
            get {
                return ResourceManager.GetString("Wizard_HeaderInstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifying {0}.
        /// </summary>
        public static string Wizard_HeaderModifying {
            get {
                return ResourceManager.GetString("Wizard_HeaderModifying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing {0}.
        /// </summary>
        public static string Wizard_HeaderRemoving {
            get {
                return ResourceManager.GetString("Wizard_HeaderRemoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repairing {0}.
        /// </summary>
        public static string Wizard_HeaderRepairing {
            get {
                return ResourceManager.GetString("Wizard_HeaderRepairing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Install.
        /// </summary>
        public static string Wizard_InstallButtonText {
            get {
                return ResourceManager.GetString("Wizard_InstallButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Next &gt;.
        /// </summary>
        public static string Wizard_NextButtonText {
            get {
                return ResourceManager.GetString("Wizard_NextButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _OK.
        /// </summary>
        public static string Wizard_OKText {
            get {
                return ResourceManager.GetString("Wizard_OKText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.perforce.com/downloads/helix-plugin-file-explorer-p4exp.
        /// </summary>
        public static string Wizard_P4EXPDownloadLink {
            get {
                return ResourceManager.GetString("Wizard_P4EXPDownloadLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        public static string Wizard_TextForLink {
            get {
                return ResourceManager.GetString("Wizard_TextForLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Uninstall.
        /// </summary>
        public static string Wizard_UninstallButtonText {
            get {
                return ResourceManager.GetString("Wizard_UninstallButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Upgrade.
        /// </summary>
        public static string Wizard_UpgradeButtonText {
            get {
                return ResourceManager.GetString("Wizard_UpgradeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1}.
        /// </summary>
        public static string Wizard_WindowTitle {
            get {
                return ResourceManager.GetString("Wizard_WindowTitle", resourceCulture);
            }
        }
    }
}
